%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/TeddyA/Drive/Research/Data/Solar/instruments/ACRIM_II.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/17 16:53:51

%% Initialize variables.
filename = 'acrimII_update.txt';
delimiter = ' ';

%% Format for each line of text:
%   columns are the following: year, month, day, julian day, number of
%   orbits with data, TSI
formatSpec = '%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ACRIM2.YEAR = dataArray{:,1};
ACRIM2.TSI = dataArray{:,2};
ACRIM2.UNCERT = dataArray{:,3};
ACRIM2.EPOCH80 = dataArray{:,4};
ACRIM2.YYMMDD = dataArray{:,5};

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;