%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/TeddyA/Drive/Research/Data/Solar/instruments/ACRIM_III.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/17 17:26:42

%% Initialize variables.
filename = 'ACRIM_III.txt';
startRow = 9;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%13f%11f%10f%11f%7s%6f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ACRIM3.YEAR = dataArray{:, 1};
ACRIM3.DAY = dataArray{:, 2};
ACRIM3.TSI = dataArray{:, 3};
ACRIM3.UNCERT = dataArray{:, 4};
ACRIM3.YYMMDD = dataArray{:, 5};
ACRIM3.MISSDAY = dataArray{:, 6};
ACRIM3.EPOCH1980 = dataArray{:, 7};

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;