%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/TeddyA/Drive/Research/Data/Solar/instruments/NIMBUS.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/17 10:25:45

%% Initialize variables.
filename = 'NIMBUS.txt';

%% Format for each line of text:
%   columns are the following: year, month, day, julian day, number of
%   orbits with data, TSI
formatSpec = '%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
NIMBUS.year = dataArray{:, 1};
NIMBUS.month = dataArray{:, 2};
NIMBUS.day = dataArray{:, 3};
NIMBUS.jd = dataArray{:, 4};
NIMBUS.orbits = dataArray{:,5};
NIMBUS.TSI = dataArray{:,6};

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;