%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/TeddyA/Drive/Research/Data/Solar/instruments/sorce.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/17 17:32:58

%% Initialize variables.
filename = 'tcte_original.txt';
startRow = 130;

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: text (%s)
%   column3: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');


%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TCTE.YYYYMMDD = dataArray{:,1};
TCTE.JDnom = dataArray{:,2};
TCTE.JDavg = dataArray{:,3};
TCTE.TSI = dataArray{:,5}; %at 1au, standard def


%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;