% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/teda/Drive/MATLAB/Gibbs/code_21_11_20/get_obs/import_scripts/instruments/VIRGO_TSI_daily_V8_20220105_accessed_22_2_2.txt
%
% Auto-generated by MATLAB on 02-Feb-2022 10:36:02

% Set up the Import Options and import the data
%opts = delimitedTextImportOptions("NumVariables", 21);
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [25, Inf];
opts.Delimiter = " ";

% Specify column names and types
%opts.VariableNames = ["UTC", "TAI", "JulianDate", "VIRGOA", "VIRGOA_B", "VIRGOAB_UNC", "VIRGOA_Correc", "VIRGOAB_correc", "start", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21"];
opts.VariableNames = ["UTC", "TAI", "JulianDate", "VIRGOA", "VIRGOA_B", "VIRGOAB_UNC", "VIRGOA_Correc", "VIRGOAB_correc"];
%opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["UTC"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["UTC"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["TAI", "JulianDate", "VIRGOA", "VIRGOA_B", "VIRGOAB_UNC", "VIRGOA_Correc", "VIRGOAB_correc"], "ThousandsSeparator", ",");

% Import the data
VIRGO = readtable("/Users/teda/Drive/MATLAB/Gibbs/code_22_06/get_obs/import_scripts/instruments/VIRGO_TSI_daily_V8b2d_June_2022_accessed_22_10_13.txt", opts);
%Two versions: V8 with no early increase, V8b with early increase  
%  /Users/teda/Drive/MATLAB/Gibbs/code_22_06/get_obs/import_scripts/instruments/VIRGO_TSI_daily_V82d_June_2022_accessed_22_10_13.txt
%  /Users/teda/Drive/MATLAB/Gibbs/code_22_06/get_obs/import_scripts/instruments/VIRGO_TSI_daily_V8b2d_June_2022_accessed_22_10_13.txt

% Clear temporary variables
clear opts