%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/teda/Drive/MATLAB/Gibbs/code_21_11_20/get_obs/other_tsi/satire_accessed_22_1_18.txt
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2022/01/18 08:57:02

%% Initialize variables.
filename = '/Users/teda/Drive/MATLAB/Gibbs/code_22_06/get_obs/other_tsi/satire_accessed_22_10_27.txt';
startRow = 25;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%12f%17f%17f%17f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
satiretsi = table(dataArray{1:end-1}, 'VariableNames', {'JD','TSI','TSI_L','TSI_H','OBS_FLAG'});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;