%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/TeddyA/Drive/Research/Data/Solar/sun/TSI_composite.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/07/08 12:57:37

%% Initialize variables.
filename = 'dudok_dewit_accessed_22_1_18.dat';
startRow = 21;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%7f%5f%5f%5f%11f%10f%10f%10f%10f%6f%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
TSIcomposite = table;
TSIcomposite.year = dataArray{:, 1};
TSIcomposite.mont = dataArray{:, 2};
TSIcomposite.hday = dataArray{:, 3};
TSIcomposite.hour = dataArray{:, 4};
TSIcomposite.julian_dat = dataArray{:, 5};
TSIcomposite.eTSIo = dataArray{:, 6};
TSIcomposite.dTSIo = dataArray{:, 7};
TSIcomposite.TSIc = dataArray{:, 8};
TSIcomposite.dTSIc = dataArray{:, 9};
TSIcomposite.nobs = dataArray{:, 10};
TSIcomposite.VarName11 = dataArray{:, 11};

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;