%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/teda/Drive/MATLAB/Gibbs/code_22_06/get_obs/other_tsi/TSI_Composite-SIST_accessed_22_09_20.txt
%
% Auto-generated by MATLAB on 20-Sep-2022 13:14:59

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = [36, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["JD", "tsi", "tsiUnc", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18"];
opts.SelectedVariableNames = ["JD", "tsi", "tsiUnc"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "JD", "TrimNonNumeric", true);
opts = setvaropts(opts, "JD", "ThousandsSeparator", ",");

% Import the data
SOLID2 = readtable("/Users/teda/Drive/MATLAB/Gibbs/code_22_06/get_obs/other_tsi/TSI_Composite-SIST_accessed_22_09_20.txt", opts);


%% Clear temporary variables
clear opts