%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/teda/Drive/MATLAB/Gibbs/code_21_11_20/get_obs/proxy_data/MgII_composite_21_11_29.dat
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2021/11/29 13:46:52

%% Initialize variables.
filename = 'MgII_extended_accessed_22_11_21.dat';
startRow = 24;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: categorical (%C)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%12f%3f%3f%8f%10C%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
MgIIcomposite = table(dataArray{1:end-1}, 'VariableNames', {'fracYr','Month','Day','mgii','uncertainty','sourceid'});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;